apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-streamlit
  template:
    metadata:
      labels:
        app: mnist-streamlit
    spec:
      containers:
      - name: mnist-streamlit
        image: gcr.io/mlops-project-8934/mnist-streamlit:v1
