apiVersion: v1
kind: Service
metadata:
  name: mnist-streamlit-service
spec:
  selector:
    app: mnist-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
